name: test

on:
  push:
    branches:
      - master

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20, 21]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependency
      run: npm i

    - name: Run tests
      run: npm run jest 

  test-macos:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [20, 21]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependency
      run: npm i

    - name: Run tests
      run: npm run jest 

  test-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20, 21]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependency
      run: npm i

    - name: Run tests
      run: npm run jest 
